In [1]:
from dataset import ProxyTaskDataset, SupervisedDataset
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import torch
import os
from time import time
print(os.getcwd())

/workspace/recvis-final-project/src_vic


In [4]:
train_set = ProxyTaskDataset()
#train_set = SupervisedDataset(train=False)
loader = DataLoader(train_set, batch_size=10, shuffle=True, num_workers=0)
#print(train_set.video_list)

In [5]:
start = time()
a = next(iter(loader))
end = time()
print(end - start)
print(a[0].size())
print(a[1])
i = a[0][0]
i = i.permute((0,2,3,1))
for k in range(10):
    fig, ax = plt.subplots(1,6, figsize=(14,14))
    #print(i.size())
    for j, im in enumerate(i[6*k:6*(k+1)]):
        im = torch.squeeze(im)
        ax[j].imshow(im.numpy())

12.791271924972534
torch.Size([10, 5, 3, 20, 224, 224])
tensor([0, 1, 1, 1, 0, 0, 1, 1, 1, 0])


RuntimeError: number of dims don't match in permute

In [5]:
from i3d import I3D
from torchsummary import summary
import torch
model = I3D(num_classes=400)
model.cuda()
model.load_state_dict(torch.load('../models/model_rgb.pth'))
summary(model, (3,10,224,224))  # Tensor dimensions = (batch_size, rgb or flow channels, nb_frames, height, width)
#zeros = torch.zeros([2,3,16,224,224]).cuda()
#out = model(zeros)
#print(out)

ModuleNotFoundError: No module named 'torchsummary'

In [5]:
import numpy as np
model_parameters = filter(lambda p: p.requires_grad, model.parameters())
params = sum([np.prod(p.size()) for p in model_parameters])
model.state_dict

<bound method Module.state_dict of I3D(
  (conv3d_1a_7x7): Unit3Dpy(
    (pad): ConstantPad3d(padding=(2, 3, 2, 3, 2, 3), value=0)
    (conv3d): Conv3d(3, 64, kernel_size=(7, 7, 7), stride=(2, 2, 2), bias=False)
    (batch3d): BatchNorm3d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (maxPool3d_2a_3x3): MaxPool3dTFPadding(
    (pad): ConstantPad3d(padding=(0, 1, 0, 1, 0, 0), value=0)
    (pool): MaxPool3d(kernel_size=(1, 3, 3), stride=(1, 2, 2), padding=0, dilation=1, ceil_mode=True)
  )
  (conv3d_2b_1x1): Unit3Dpy(
    (conv3d): Conv3d(64, 64, kernel_size=(1, 1, 1), stride=(1, 1, 1), bias=False)
    (batch3d): BatchNorm3d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (conv3d_2c_3x3): Unit3Dpy(
    (conv3d): Conv3d(64, 192, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1), bias=False)
    (batch3d): BatchNorm3d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (maxPool3d_3a_3x3): MaxPool3dTFPaddi

In [1]:
run self_supervised_main.py --n_samples=10 --batch-size=64 --lr=0.001 --log-interval=1

Using GPU


/workspace/recvis-final-project/src/odd_one_out.py:24: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  output = F.softmax(self.fc2(x))


Train Epoch: 1 [0/9060 (0%)]	Loss: 1.792662
Train Epoch: 1 [64/9060 (1%)]	Loss: 1.791584
Train Epoch: 1 [128/9060 (1%)]	Loss: 1.791484
Train Epoch: 1 [192/9060 (2%)]	Loss: 1.793214
Train Epoch: 1 [256/9060 (3%)]	Loss: 1.791607
Train Epoch: 1 [320/9060 (4%)]	Loss: 1.792535
Train Epoch: 1 [384/9060 (4%)]	Loss: 1.792770
Train Epoch: 1 [448/9060 (5%)]	Loss: 1.791625
Train Epoch: 1 [512/9060 (6%)]	Loss: 1.792941
Train Epoch: 1 [576/9060 (6%)]	Loss: 1.792889
Train Epoch: 1 [640/9060 (7%)]	Loss: 1.792939
Train Epoch: 1 [704/9060 (8%)]	Loss: 1.790715
Train Epoch: 1 [768/9060 (8%)]	Loss: 1.789815
Train Epoch: 1 [832/9060 (9%)]	Loss: 1.789587
Train Epoch: 1 [896/9060 (10%)]	Loss: 1.793673
Train Epoch: 1 [960/9060 (11%)]	Loss: 1.791945
Train Epoch: 1 [1024/9060 (11%)]	Loss: 1.789289
Train Epoch: 1 [1088/9060 (12%)]	Loss: 1.789991
Train Epoch: 1 [1152/9060 (13%)]	Loss: 1.790879
Train Epoch: 1 [1216/9060 (13%)]	Loss: 1.791179
Train Epoch: 1 [1280/9060 (14%)]	Loss: 1.791478
Train Epoch: 1 [1344/9060

NameError: name 'device' is not defined

In [ ]:
run evaluateO3N.py --model='experiment/model_2.pth' 

Using GPU
GPU usage:
  memory.used memory.free
0   11374 MiB     832 MiB
1      11 MiB   12195 MiB
Using GPU1 with 12195.0 free MiB
1
2
3


In [17]:
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

features = np.load('precalculated_features.npy')
labels = np.load('labels.npy')

X_train, X_test, y_train, y_test = train_test_split(features, labels, random_state=5)

model = SVC(gamma='auto')
model.fit(X_train, y_train)
print(model.score(X_train, y_train))
print(model.score(X_test, y_test))

/root/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.030771372876636033
0.02763661677688827


In [12]:
features = np.stack(features)

In [13]:
features.shape

(118, 1024)

In [6]:
run create_feature_file.py

In [ ]:
run svm.py

129498
129498
6684
6684


In [1]:
run self_supervised_main.py

Using GPU
GPU usage:
  memory.used memory.free
0   11801 MiB     405 MiB
1      11 MiB   12195 MiB
Using GPU1 with 12195.0 free MiB


/root/anaconda3/lib/python3.6/site-packages/torch/nn/_reduction.py:16: UserWarning: reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.
  warnings.warn("reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.")


tensor([[[0.4853, 0.4827, 0.4769, 0.4918, 0.4775],
         [0.5147, 0.5173, 0.5231, 0.5082, 0.5225]],

        [[0.5251, 0.5347, 0.5329, 0.5241, 0.5337],
         [0.4749, 0.4653, 0.4671, 0.4759, 0.4663]],

        [[0.4601, 0.4581, 0.4713, 0.4769, 0.4480],
         [0.5399, 0.5419, 0.5287, 0.5231, 0.5520]],

        [[0.5200, 0.5101, 0.5325, 0.5101, 0.5081],
         [0.4800, 0.4899, 0.4675, 0.4899, 0.4919]],

        [[0.5012, 0.4979, 0.4901, 0.4838, 0.4986],
         [0.4988, 0.5021, 0.5099, 0.5162, 0.5014]],

        [[0.5187, 0.5108, 0.5312, 0.5228, 0.5228],
         [0.4813, 0.4892, 0.4688, 0.4772, 0.4772]],

        [[0.5063, 0.4922, 0.4906, 0.4788, 0.4753],
         [0.4937, 0.5078, 0.5094, 0.5212, 0.5247]],

        [[0.5135, 0.5091, 0.5039, 0.5128, 0.5110],
         [0.4865, 0.4909, 0.4961, 0.4872, 0.4890]]], device='cuda:1')
tensor([[0.4828, 0.5172],
        [0.5301, 0.4699],
        [0.4629, 0.5371],
        [0.5161, 0.4839],
        [0.4943, 0.5057],
        [0.5213, 0.47

KeyboardInterrupt: 